server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reel_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

app:
  jwt:
    secret: "JmOhT73SmmCi6kilzNi07YGh1ZAq3rBcbZV1CCiXzW0="
  upload:
    dir: uploads/videos
